"""empty message

Revision ID: b9ff276710cb
Revises: 1644d90afd7b
Create Date: 2025-07-13 16:16:22.707739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9ff276710cb'
down_revision = '1644d90afd7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.drop_constraint('personajes_especie_key', type_='unique')

    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.drop_constraint('planetas_clima_key', type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=128),
               existing_nullable=False)

    with op.batch_alter_table('usuario_personaje', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('personajes_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('usuario_planetas', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('planetas_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario_planetas', schema=None) as batch_op:
        batch_op.alter_column('planetas_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('usuario_personaje', schema=None) as batch_op:
        batch_op.alter_column('personajes_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    with op.batch_alter_table('planetas', schema=None) as batch_op:
        batch_op.create_unique_constraint('planetas_clima_key', ['clima'])

    with op.batch_alter_table('personajes', schema=None) as batch_op:
        batch_op.create_unique_constraint('personajes_especie_key', ['especie'])

    # ### end Alembic commands ###
